language: go

before_install:
  - make install

notifications:
  email: true

matrix:
  include:
    - stage: vet
      script:
        - make vet
    - stage: lint
      script:
        - make lint
    - stage: security-check
      script:
        - make security-check
