language: go

before_install:
  - make install

notifications:
  email: true

matrix:
  include:
    - stage: vet
      script:
        - make vet
    - stage: lint
      before_script:
        - go get golang.org/x/lint/golint
      script:
        - make lint
    - stage: security-check
      before_script:
        - go get github.com/securego/gosec/cmd/gosec
      script:
        - make security-check
