language: go
go: 1.13.x

before_install:
  - make install

notifications:
  email: false

matrix:
  include:
    - stage: Build
      script:
        - make vet
        - make lint
        - make security-check
